version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./deployment/nginx/Dockerfile
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./deployment/api/Dockerfile
    image: mapi:latest
    container_name: mapi
